name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Hosting
        run: npm install
      - name: Install Functions
        run: npm --prefix functions install
      - name: Lint Hosting
        run: npm run lint
      - name: Lint Functions
        run: npm --prefix functions run lint
      - name: Build Hosting
        run: npm run build
      - name: Build Functions
        run: npm --prefix functions run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
