name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install
        run: npm install
      - name: Install Functions
        run: npm --prefix functions install
      - name: Build
        run: npm run build
      - name: Build Functions
        run: npm --prefix functions run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: libFunctions
          path: functions/lib
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Download Artifact Functions
        uses: actions/download-artifact@master
        with:
          name: libFunctions
          path: functions/lib
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
